### PR TITLE
OAuth2-esque User Sign In

### PR DESCRIPTION
**Pull request by ryanmcgrath**
In the interest of reducing user sign-in friction, I took a look at adding in an OAuth2-esque experience.

This changes the approach that was used prior in `SlippiUser.cpp`, where the user would be popped over to a browser and made to download a file - while it works, it often causes confusion due to where the file needs to sit. Go figure.

To make this easier, I've added `--enable-webview` to the wxWidgets build, and swapped out the code to throw the user to a browser, and made a browser window popup that can save their `user.json` for them. In my testing on macOS this works very well, and Linux should theoretically be fine due to the pervasiveness of Webkit there, but Windows might be tricky if it uses IE.

This required some server side changes that Fizzi has already pushed, so it should be test-able now.

### CODE REVIEW

**Comment by ryanmcgrath** [comment]
Clearly there are some spacing/indentation issues that I'm not fixing tonight, lol

Will look at them tomorrow

**Comment by ryanmcgrath** [comment]
Ah, and in the interest of transparency: `BrowserControl` on Windows seems to emulate IE7 (!?) by default.

[However... it looks like this can be controlled, to at least enforce IE11](https://docs.wxwidgets.org/trunk/webview_8h.html#a7966c47cdf6c2fb43386a3c02f6693b6) as of 3.1.3.

It would appear that there's also an Edge backend that can be made to work, [as documented here](https://docs.wxwidgets.org/trunk/classwx_web_view.html). The features that are "unsupported" in Edge are not needed for this functionality, thankfully.

**Comment by ryanmcgrath** [comment]
Hmm, Windows I understand failing, but Linux is strange - builds fine on my Ubuntu machine. Perhaps a CI wizard can weigh in tomorrow, otherwise I'll have to poke at it I guess.

**Comment by a-sink-a-wait** [comment]
I'm taking a look at the Ubuntu build. I see that we added some new builds for `Playback` and `Netplay` though at first glance they look similar, which is concerning.

I'll dig in a bit more.

**Comment by a-sink-a-wait** [comment]
Aright so after some brief digging, here's my best guess for now.

First off, it looks like the builds are failing on the `wxWidgets` dependencies. I didn't look at the code checked in, but it looks like the installation of these dependencies differs between Ubuntu and macOS.

macOS seems to handle these dependencies "out of the box" while the Ubuntu installation is calling the following in it's prequisites:

```           
libwxbase3.0-dev \
libwxgtk3.0-dev \
```

@ryanmcgrath Have you done any updates to the wxWidgets in order to support this feature? Perhaps a package that gets installed on macOS implicitly that needs an explicit install in Ubuntu?

**Comment by a-sink-a-wait** [comment]
Would you be able to run this step as is from the `macOS` build in the `Ubuntu` build?

```yaml
- name: "Install wxWidgets 3.1.3"
        if: success()
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          cd wxWidgets-3.1.3
          cd build
          ../configure
          make -j7
          sudo make install
```

Also it looks like there might be a version mismatch between the builds. Ubuntu is referencing `3.0` paths while macOS installs `3.1.3` not sure if that matters.

**Comment by ryanmcgrath** [comment]
Eh, so the thing is I don't think it's that that's the issue - yes, wxWidgets needs to be built with `--enable-webview` for this to work, but the Linux build works fine in my Ubuntu instance if I use the CI instructions from my fork (updated to use the `libwxgtk3.0-dev`). I think I'm more interested in whether this is a CI caching issue, or some mismatch elsewhere.

I'll dig in tonight I guess.

**Comment by a-sink-a-wait** [comment]
> I think I'm more interested in whether this is a CI caching issue, or some mismatch elsewhere.

I can say with about 90% certainty that it is not that. Agents that run in github actions are ephemeral. You can lookup pre-installed software of these agents when your action "gets them", and that's the state that the agent is in at the start of the first step.

The subsequent steps of each job are run on the same agent; separate agent for each job. The state is fresh each time (aside from preinstalled and running software). Perhaps the issue is with compatibility with some software on the agents. I don't have enough knowledge to tell you if that's the case for this particular project.

If i'm missing something, I'd be interested to know what.

**Pull request closed without merging**
