### PR TITLE
Add simple stack trace on unhandled exception

### LINKED ISSUE #43: Log stack trace to file on unhandled exception
Users are seeing Dolphin crash with no way to figure out what was causing the crash. We need the stack trace to be written to the `User/Logs` folder as `stacktrace.txt` (append by default) whenever an unhandled exception occurs.

### PR DESCRIPTION
**Pull request by ngullotta**
Fixes #43 
This leverages wxStackWalker and the OnFatalException handler to
access frames and their associated data

### CODE REVIEW

**Comment by JLaferri** [comment]
Tested this on windows. Did not seem to work for me unfortunately :(

https://github.com/project-slippi/Ishiiruka/tree/pr/78

**Comment by ngullotta** [comment]
Hmm. I did not try this on Windows, but I don't see any reason why this _wouldn't_ work on Windows.

Is the `OnFatalException` function being called at all for you?

Can you try enabling the `wxUSE_STACKWALKER` and/or `wxUSE_ON_FATAL_EXCEPTION` flags?

**Comment by JLaferri** [comment]
Honestly I'm having a lot of trouble telling whether the function is being called at all. If I run it in debug mode in VS, it stalls on the exception itself and never gets there. And if I run the compiled version it just crashes and I don't see anything.

I tried adding logging in the function but it's always possible it is calling the loggers but terminating the app too fast for them to get written?

You can see what I've tried in the PR link I sent before. It's very possible I'm doing something wrong

**Comment by ngullotta** [comment]
I'll check it out on Windows when I have some free time

**Comment by ngullotta** [comment]
I did fix one issue where the path was all borked up on Windows, but, like yourself, I cannot get `OnFatalException` to be called at _all_, will investigate further.

Feel free to close this pr until then.

**Comment by JLaferri** [comment]
Thanks for checking. I think it's fine to keep open as this is a feature we would really like.

**Comment by ngullotta** [comment]
I have an idea as to what the issue could be but I cannot get a local build running due to my inability to duck the "Precompiled Header Setting"

My idea was this, if you want to try it yourself pending my testing:

I read somewhere on wxWidget's documentation that OnFatalException depends on a compiling with Structured Exception Handling as a feature. This is a feature in Visual Studio.

See this Microsoft documentation on the option here:
https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=vs-2019#to-set-this-compiler-option-in-the-visual-studio-development-environment

Now, here comes the janky part. I tried doing this for myself after rebasing my branch on upstream slippi, but I _cannot_ get it to compile. It always says

```
compiler option 'C++ Exception Handling Unwinding' inconsistent with precompiled header; current command-line option will override that defined in the precompiled header
```
I tried disabling PCH and then get hit with even more errors, so I decided to stop there for now.

You might try enabling this yourself and see if you can get past this error. With any luck, this is what's preventing this feature from working on Windows.

**Comment by JLaferri** [comment]
@legionxvx Did you update to VS2019? Wondering if that's why you encountered errors.

Fwiw Dolphin doesn't support C++ exceptions afaik, you can't use try/catch

**Comment by NikhilNarayana** [comment]
Closing due to inactivity.

**Pull request closed without merging**
