### PR TITLE
Spectator Server Feature

### PR DESCRIPTION
**Pull request by altf4**
- Enabled via config: SlippiEnableSpectator = true (default false)
 - Opens local ENet server on UDP port 51441
 - Sends SLP game / menu events wrapped in JSON
 - Punches a hole through NAT to IP/port specified in slippispectatorip and slippispectatorport

To Test: 
- Use the Slippi Launcher: (Updated for this functionality here: https://github.com/altf4/slippi-desktop-app/tree/spectator)
- We'll have the following setup: 
- User A playing a match on Slippi Online with a typical home NAT router.
- User B: Running the Slippi Launcher from a different remote network from User A, also behind a typical NAT router
- User A and B look up their external IPv4 IPs (such as by going to whatsmyip.org) and tell them to each other out-of-band.
- User A: Go to `Dolphin.ini` and set `SlippiEnableSpectator = true` and `slippispectatorip = <IP OF User B>`
- User B: Start Slippi Launcher and make a new Console Connection, enter User A's IP for the console's IP.
- User A: Start Dolphin and play games! Any matches played (online or offline) will be streamed to User B. (Will be written to SLP file and can be mirrored to view live)

Additionally:
- Use libmelee: (Updated for this functionality here: (https://github.com/altf4/libmelee/)

~Known Issue 1: Opponent LRAS in online game ends uncleanly.~ 
~For some reason when the opponent hits LRAS in a game, the end-game event never gets written to SLP file, nor sent to the spectator. This is not a bug in the Spectator code, but relevant since the game stream doesn't end properly.~
EDIT: Fixed as of the latest ASM code. 

Known Issue 2: The Electron Launcher app has a performance issue. Will need to investigate
- When a game lasts longer than a few minutes, the launcher starts to fall behind in game events, struggles to keep up hard, and then eventually just dies and becomes totally unresponsive. 
- This is 100% not a bug in the spectator code, as libmelee (a python client) is able to receive these messages just fine. (I can reliably receive messages with sub-frame latency for whole matches with no drops)

### CODE REVIEW

**Comment by altf4** [comment]
(fyi: the slippispectatorip config option is really only for NAT hole punching. If you're on the local network, then you can just connect without setting this)

**Comment by a-sink-a-wait** [comment]
Awesome write up 👍 
Gonna take a look and get familiar

**Comment by altf4** [comment]
Weird. This builds and runs on my VS 2019 machine. Don't know why the CI failed?

**Comment by altf4** [comment]
What?! The playback build definitely builds for me. I don't understand what's going on.

**Pull request merged**
