### PR TITLE
Feature - Recent opponents list

### PR DESCRIPTION
**Pull request by CharlesAMiller**
Initial work to implement some of the features outlined in: #125 . 

The feature implements the proposed behavior, as detailed by @JLaferri below.
 
> First, Dolphin side you're going to need:
>
>  1. Hook into the CMD_FIND_OPPONENT handler. When find match is triggered for direct, you'll need to grab the requested >  connect code and save it to some file probably.
>  2. Prob best to keep the list unique? So if you get a connect code that has been used before, move it to the front of the list >  and get rid of the old entry.
>  3. EXI Handler for new command to fetch a connect code to return to the game, maybe would take an index as an input arg?  Something like that

image

### CODE REVIEW

**Comment by JLaferri** [comment]
I think the R and L are way too big. I also think that having it look like `<L` and `R>` might look more natural.

Additionally seems like the mac/linux builds are broken, probably the new file needs to be added to cmakelists

**Comment by CharlesAMiller** [comment]
I'll add the files to the cmakelists momentarily. And I'll tinker some with the styling soon. How do you feel about the color of the text? I was going back and forth on maybe trying to have it be closer to the color of the keyboard entries.

**Comment by NikhilNarayana** [comment]
don't worry about fixing cmake, i tested on my linux machine and fixed the build entirely

**Comment by NikhilNarayana** [comment]
Apparently Clang doesn't like using strings for `%s` so just make them all use c_str()

**Comment by CharlesAMiller** [comment]
New styling per @JLaferri's comment. 

image

**Comment by JLaferri** [comment]
Nice looks better. I'll try to give this a test myself at some point. I talked to Bazoo on Discord about something I think would actually make this feature much stronger but would make it much harder to implement.

It would be great if entering codes supported auto-complete based on codes you've used before. So for example if I've used codes AB#344 and AC#123 and I type A, it would filter the recent list based on codes that start with A and show the most recent as like:

A in white text, and then the completion: B#344 in grayed out text. Then you could hit a button to accept the suggestion or continue typing to filter further.

Should make it much easier to find any codes you've used before... If using L/R without typing anything, the names would show up fully gray and you'd still have to press the button to accept and turn the name white to use it.

**Comment by JLaferri** [comment]
Part of the reason I suggest the above is that I'm somewhat concerned in its current iteration, people will actually end up wasting time searching for a name that might be like 8+ names deep when it probably would have been faster to just type it out lol

**Comment by CharlesAMiller** [comment]
That does sounds like a useful feature. I still don't know too much about drawing things in-game, but I'll see what I can do.

**Comment by CharlesAMiller** [comment]
I've added an autocomplete feature per @JLaferri's recommendation. Pressing start will complete an autocomplete suggestion.

**Comment by JLaferri** [comment]
Oooo exciting. Do you have a video showcasing the functionality?

**Comment by CharlesAMiller** [comment]
> 
> 
> Oooo exciting. Do you have a video showcasing the functionality?

While the [video ](https://drive.google.com/file/d/1LR_-bQwwcN7DPWI7NfmfQWAfy33UPjWk/view?usp=sharing) doesn't show me connecting to an individual, it does in fact work. In the video, I first use the right trigger twice to navigate through two saved entries. From there, I begin typing a different tag. Once I've entered "A", the autocomplete text changes to, "DANK#166". Upon pressing start, the autocompleted text is accepted and the color of the text changes. Additionally, the navigation cursor is moved to the Confirm option.

**Comment by JLaferri** [comment]
That looks awesome. I'll give it a try tomorrow.

**Comment by JLaferri** [comment]
Testing this now. Will write notes with bugs/requested changes.

- Pressing R before doing anything else when in the name entry screen causes a game crash
- Pressing start with suggestion showing gives error message
- When there is a suggestion visible, scrolling to confirm and pressing A submits the code with the suggestion instead of just the dark letters
- Pressing B clears suggestion. Should probably clear a letter instead
- Index of suggestion seems to be preserved across entering the name entry screen. Should reset

Anyway the progress looks really nice. Had too many issues to fully use it right but I'm really optimistic about this. Happy to talk through the issues with you as well.

**Comment by NikhilNarayana** [comment]
Some quick notes after testing with the latest changes here and from the ASM PR.
- Pressing R when you have nothing in your history causes a crash.
- It isn't that clear how to accept a suggestion, at first I thought I needed to press R and then I had to ask Fizzi to find out it was start.
- If you type in something like VA#987 or Q#214 then only the first 3-4 characters get read for some reason (so VA#987 -> VA#9 and Q#214-> Q#2)
- if you hit the random button, the 4th character is always "incomplete" (lighter text)

You should rebase or merge slippi so you can fix CI btw.

**Comment by CharlesAMiller** [comment]
> 
> 
> Some quick notes after testing with the latest changes here and from the ASM PR.
> 
>     * Pressing R when you have nothing in your history causes a crash.

I think I've resolved this one.

>     * It isn't that clear how to accept a suggestion, at first I thought I needed to press R and then I had to ask Fizzi to find out it was start.
> 

I've moved the autocomplete button to Z, per our previous conversation.

>     * If you type in something like VA#987 or Q#214 then only the first 3-4 characters get read for some reason (so VA#987 -> VA#9 and Q#214-> Q#2)

I *think* I've got this one fixed. I've done some testing, specifically with those example tags, and it appears to be resolved.

>     * if you hit the random button, the 4th character is always "incomplete" (lighter text)
> 

I'm looking into this one right now, but I thought it might be worth checking in with my current progress.

> You should rebase or merge slippi so you can fix CI btw.

Hope I did it right this time around. I'm still pretty novice at collaborating with Git.

**Pull request merged**
