### PR TITLE
Add connect codes to game info response

### PR DESCRIPTION
**Pull request by jmlee337**
Must ship in the same release as https://github.com/project-slippi/slippi-ssbm-asm/commit/85dc6e4a3ff9dabb658fc3cfacb69c8fa3f7ec71

not sure what branch this should be merged into...

### CODE REVIEW

**Comment by jmlee337** [comment]
now supports doubles

**Comment by jmlee337** [comment]
see https://github.com/project-slippi/slippi-ssbm-asm/pull/51

**Comment by jmlee337** [comment]
I caught a mistake in the 'real' (non local testing) codepath in review, so I will try to test this build for real just in case

**Comment by jmlee337** [comment]
just as an update, I was able to test 1v1 on two separate machines, but I haven't wrangled the people necessary to do a proper doubles test yet.

**Comment by jmlee337** [comment]
I've confirmed this works with 4 players. Here's a sample replay:
[Game_20210129T145218.zip](https://github.com/project-slippi/Ishiiruka/files/5891920/Game_20210129T145218.zip)

**Comment by JLaferri** [comment]
Cool, thanks. Will try to merge into release branch once we have more code space

**Comment by jmlee337** [comment]
tested with merged changes, seems to work. However I did have to rebuild bootloader.gct the asm repo and copy it in. Should I include that in a commit?

**Pull request merged**
