### PR TITLE
Improve Network stability

### PR DESCRIPTION
**Pull request by rapito**
This PR makes Netplay experience more stable in case of emulation inconsistencies.

- a singleton slippi_netplay is exposed to be available throughout the codebase

### CODE REVIEW

**Comment by JosJuice** [comment]
Keep in mind that `SetState` also is called in situations other than the specific action you are trying to prevent. I believe this PR breaks screenshots the way it currently is implemented (or at least adds some sort of race condition to them).

**Comment by JLaferri** [comment]
Does this PR also handle emulation speed changes?

**Comment by JLaferri** [comment]
> Keep in mind that `SetState` also is called in situations other than the specific action you are trying to prevent. I believe this PR breaks screenshots the way it currently is implemented (or at least adds some sort of race condition to them).

Are screenshots like user screenshots? Haven't really heard of that feature, do you think it's something Melee players use?

**Comment by rapito** [comment]
@JLaferri  
> Does this PR also handle emulation speed changes?

~Nope~ Yes

@JosJuice
> Keep in mind that `SetState` also is called in situations other than the specific action you are trying to prevent. I believe this PR breaks screenshots the way it currently is implemented (or at least adds some sort of race condition to them).

Stability is better if screenshots are disabled when playing online. ~That said, this does not break screenshots you can still take them. But I think it's best to remove them so I will add that on my next commit.~ The user can simply user their OS screenshot feature.

**Comment by JosJuice** [comment]
> Are screenshots like user screenshots? Haven't really heard of that feature, do you think it's something Melee players use?

Yeah, the user presses a button and Dolphin saves a screenshot of the game to a file. You can do it with a button in the GUI or with a hotkey. As for whether Melee players use it, you probably know better than me :)

**Comment by seankhl** [comment]
If all this does is disable Dolphin features that can cause state changes in the emulation that can affect netplay stability, then it seems like a no-brainer to merge. Improving stability at the cost of non-critical features seems definitely worthwhile to me. The question is if disabling these things can actually be shown to improve stability. Is it just speculation, or has it been shown concretely?

**Pull request merged**
