### PR TITLE
Updated Windows SDK Version in the README

### PR DESCRIPTION
**Pull request by rfeesh**
This fixes the required Windows SDK version in the README to match the required version in the solution file.

### CODE REVIEW

**Comment by NikhilNarayana** [comment]
LGTM, thanks

**Comment by kevthompson** [comment]
The new version# is still wrong, should be 10.0.15063.0

**Comment by NikhilNarayana** [comment]
yeah that was my bad, it is fixed now.

**Comment by rfeesh** [comment]
Oops I had that shifted by a digit my bad

**Pull request merged**
