### PR TITLE
Fixing Cmake error on ARM Platforms

### PR DESCRIPTION
**Pull request by FranLMSP**

### CODE REVIEW

**Comment by eigenform** [comment]
Is this a work-in-progress or is this usable? I don't have any ARM machines to test this on.

**Comment by FranLMSP** [comment]
> Is this a work-in-progress or is this usable? I don't have any ARM machines to test this on.

it's a work-in-progress, it doesn't fully complie yet due to incompatibilities with the `GenericTextureDecoder.cpp` file 😥

**Comment by cobalt2727** [comment]
any updates or should ARM users wait for the move to using mainline Dolphin as a base rather than Ishiiruka?

**Comment by FranLMSP** [comment]
@cobalt2727 I would prefer to wait for the mainline Dolphin which has better support for AMR, I gave up trying to fully compile this on my Raspberry, there's a bunch of broken stuff lol

**Comment by ryanmcgrath** [comment]
Eh, if either of you is interested, I have a branch that I was tinkering with for Apple's M1. Mostly fixes up build issues and makes the Generic Texture Coder actually compile (I have no idea where that file is originally from, era-wise, but it made no sense). It's likely a no-go on M1 due to performance reasons, but you're welcome to tinker with it on a Pi if you want - should only need minor modifications for non-Apple ARM platforms. I believe one other person has gotten it compiled on a Raspberry Pi 4b, which to my knowledge is the only one that can do OpenGL 3 (which is what's needed to run this).

YMMV, no guarantees, etc.

https://github.com/ryanmcgrath/Ishiiruka/tree/experiment/apple-m1-native

It's not up to date with newer Slippi commits and it's not an official Slippi build nor supported by them.

**Comment by b3nd3r-ssbm** [comment]
I'm the person who got it compiled on a pi but I have not gotten it to run due to OpenGL errors, it seems like 2.1 is the highest GL goes on pi, whereas GLES goes to 3.x

**Comment by FranLMSP** [comment]
@b3nd3r-ssbm yeah opengl is a bit tricky even with mainline Dolphin on the Pi. Did you compile it with the `USE_EGL` flag in CMakeList.txt (https://github.com/project-slippi/Ishiiruka/pull/176/commits/478f71ca074a76c8fa6d59fb3577c9c918d5a337) and set the `PreferGLES = True` in the `GFX.ini` file?

**Comment by b3nd3r-ssbm** [comment]
> @b3nd3r-ssbm yeah opengl is a bit tricky even with mainline Dolphin on the Pi. Did you compile it with the `USE_EGL` flag in CMakeList.txt (https://github.com/project-slippi/Ishiiruka/pull/176/commits/478f71ca074a76c8fa6d59fb3577c9c918d5a337) and set the `PreferGLES = True` in the `GFX.ini` file?

@FranLMSP Yes, I did. It still errors out when I try opening a game, although the app does run.

**Pull request closed without merging**
