### PR TITLE
Stop rumble when game ends

### LINKED ISSUE #327: Rumble continues after L-R-A-Start
If either player stops the game with an L-R-A-Start, the controller will keep rumbling at the same force as it was at the time of the input.

## Expected Behavior

The controller stops rumbling when going back to the CSS screen.

## Current Behavior

The controller keeps rumbling during the CSS screen.

## Steps to Reproduce

1. Enable rumble
2. Start a game
3. Self-destruct
4. L-R-A-Start while hitting a blast zone (it's the most consistent way triggering the rumble)
5. The controller will keep rumbling

## Environment
Windows 10
MayFlash Adapter

### PR DESCRIPTION
**Pull request by beaudry**
Fixes #327

I'm not sure if the header should be placed alphabetically, or with the other common headers

### CODE REVIEW

**Comment by JLaferri** [comment]
I don't think doing this in Dolphin is correct. This should be handled by the game. We tried to fix it at one point and it didn't work. Also I was never able to repro this reliably. If you can find a way to repro it 100% of the time that would help us fix it for sure.

**Comment by beaudry** [comment]
I found the ASM repo after having done this PR, and I agree that it would be preferable to have the game handle it.

My way of testing was by doing L-R-A-Start while hitting a blastzone.

Should I start learning asm? 😛

**Comment by beaudry** [comment]
I just tried and I did it 20 times in a row without any problem (using LOCAL_TESTING)

Update: for the first L-R-A-Start, the rumble stops correctly, but the rumble stays for the rest

**Comment by JLaferri** [comment]
Can you explain your repro steps exactly? I know you posted it in the issue but the more specific the better.

**Comment by beaudry** [comment]
Here's [everything I found about the Slippi rumble bug](https://www.youtube.com/watch?v=KpXcAl1HVuE) 🙂

In summary:
- Never happens on the first LRAS
- Never happens on port 1 and 2
- Happens each subsequent reset on port 3 & 4
- [Not shown on the video] Disconnecting from the opponent changes nothing
- [Not shown on the video] The same behaviour happens in teams

_Hypothesis_: The "stop rumbling" signal is sent to the in-game player port, and that port is never redirected to the actual port. Hence why it works when plugged in port 1 & 2. Maybe the port redirection is destroyed before the rumble signal is sent?

**Comment by JLaferri** [comment]
> Here's [everything I found about the Slippi rumble bug](https://www.youtube.com/watch?v=KpXcAl1HVuE) 🙂
> 
> In summary:
> 
> * Never happens on the first LRAS
> * Never happens on port 1 and 2
> * Happens each subsequent reset on port 3 & 4
> * [Not shown on the video] Disconnecting from the opponent changes nothing
> * [Not shown on the video] The same behaviour happens in teams
> 
> _Hypothesis_: The "stop rumbling" signal is sent to the in-game player port, and that port is never redirected to the actual port. Hence why it works when plugged in port 1 & 2. Maybe the port redirection is destroyed before the rumble signal is sent?

Excellent research and thanks for the super detailed video! I think your hypothesis is likely. It also explains why I was never able to repro it since I play in port 1/2 generally.

I'll look into it more closely.

**Comment by beaudry** [comment]
Great! Can you keep me updated too? I'm really interested on how to fix it, and espescially why the bug doesn't occur the first time. 😃 

Happy Holidays too 🎄

**Comment by JLaferri** [comment]
Okay so I "fixed" the issue. I write fixed in quotes because it isn't exactly the most fulfilling fix. In truth I worked around the issue. I unfortunately don't know enough about how rumble goes from game state -> controller rumble update well enough to be able to debug the issue directly.

Unfortunately we just did a release so likely it'll be a bit before this fix goes live.

You can find more info about the "fix", along with some of my debugging notes in the PR: https://github.com/project-slippi/slippi-ssbm-asm/pull/85

**Comment by JLaferri** [comment]
The fix for this was released yesterday but it seems like this issue can still happen. Might need to figure out steps to reproduce it with the new changes now...

https://twitter.com/Fizzi36/status/1491227558343737344?s=20&t=ngd_Lh9lZ5bt7c3RGwL-1w

**Comment by beaudry** [comment]
Hmm, maybe the fix worked only when the L - R - A - Start happens on the client side. We'd have to test with two real players.

Also, Axe was playing on port 1, which is different from before

**Comment by JLaferri** [comment]
> Hmm, maybe the fix worked only when the L - R - A - Start happens on the client side. We'd have to test with two real players.
> 
> Also, Axe was playing on port 1, which is different from before

Yeah I noticed that too. I haven't heard anyone report it since then though... we had some minor issues right after launch so I wonder if it was related to that.

**Pull request closed without merging**
