### PR TITLE
Add slippicomm functionality

### PR DESCRIPTION
**Pull request by altf4**
Add slippicom functionality to dolphin
     - Emulates (mostly) slippicom functionality as seen on console
     - Opens socket on TCP port 51441
     - Sends a history of events back to those who enter mid-match
     - Clears the history on match-end

Built and tested on Linux (Ubuntu 18.04) and Winows 10.

### CODE REVIEW

**Comment by altf4** [comment]
Can test the functionality by starting a match and running (from Linux and OSX anyways):

~~`nc 127.0.0.1 51441 | xxd`~~
EDIT: Note to testers: Slippicomm on Nintendont requires that you do a handshake first, so my PR now emulates this too. IE: You can't just passively listen, you need to send a handshake message first. IE: netcat won't work for a listener

**Comment by altf4** [comment]
Needs to be tested on OSX still. I don't have a mac.

**Comment by altf4** [comment]
Okay, this latest push (squashed down, so force-pull) should contain a working implementation that is pretty clean. 

Tested on Windows and Linux. 

When (or perhaps if) the ENet code winds up running on Nintendont, I'll replace this with ENet code. But for now, this does a good job of emulating Wii network behavior.

**Comment by altf4** [comment]
Oh, actually there's one thing I know still has to be done. I'm just not sure how to in Dolphin. These values should be read from config or something, not hardcoded:

https://github.com/altf4/Ishiiruka/blob/slippicom/Source/Core/Core/Slippi/SlippicommServer.cpp#L378
and
https://github.com/altf4/Ishiiruka/blob/slippicom/Source/Core/Core/Slippi/SlippicommServer.cpp#L267

**Comment by altf4** [comment]
Added support for menu state information to the PR. (It's actually ready this time, and I didn't accidentally push :p )

**Comment by altf4** [comment]
ASM for menu state is here: https://github.com/altf4/slippi-ssbm-asm/blob/master/Output/Netplay/GALE01r2.ini

And to actually read it from the application layer (Launcher ignores the messages), you might want libmelee: https://github.com/altf4/libmelee/

**Comment by andrralv** [comment]
I can test and file issues if instructions are provided. I ran the build on Dolphin and the screen shows "Log-in. Access the instructions to log-in" but there are no instructions for logging in in the downloaded zip nor in the repo root.

**Comment by NikhilNarayana** [comment]
> I can test and file issues if instructions are provided. I ran the build on Dolphin and the screen shows "Log-in. Access the instructions to log-in" but there are no instructions for logging in in the downloaded zip nor in the repo root.

this isn't ready for testing yet, but when altf4 fixes the merge conflicts it can be tested.

**Comment by leoleotte** [comment]
I'm testing altf4's branch extensively with the slippi-desktop-app and custom TCP sockets written in Python and it's looking all good

**Comment by altf4** [comment]
I have a new version of this that substantively changed. I rebased it and am submitting a different PR to keep it clean.

**Pull request closed without merging**
